/**
 * Drive probe — capture the screenshot set the docs website ships.
 *
 * Every image under `website/public/shots/` is generated by this probe from
 * the real app driving the real example project, so the docs can never drift
 * into showing a UI that no longer exists: re-run it and the tour re-renders.
 *
 * Run:  node scripts/e2e/drive.mjs --boot --example
 *       node scripts/e2e/drive.mjs scripts/e2e/probes/docs-shots.mjs
 *       node scripts/e2e/drive.mjs --stop
 *
 * Shots land at 1600×1100 CSS px / dpr 2 (3200×2200 PNG) — drive.mjs pins
 * that viewport on attach. Pass SUNA_SHOTS_ONLY=name,name to capture a
 * subset while iterating on one page of the site.
 */
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readdirSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..')
const OUT = join(ROOT, 'website', 'public', 'shots')

/**
 * Shots are captured to a staging dir OUTSIDE the repo and copied in at the
 * end. Writing PNGs under the repo root mid-run trips the Vite dev server's
 * file watcher, which full-reloads the renderer and takes `window.__sunaDev`
 * — and the open project — down with it, so every shot after the third used
 * to fail. One copy burst after the last capture is invisible to the run.
 */
const STAGE = mkdtempSync(join(tmpdir(), 'suna-docs-shots-'))

const only = (process.env.SUNA_SHOTS_ONLY ?? '')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean)

export default async (ctx) => {
  mkdirSync(OUT, { recursive: true })

  await ctx.waitFor(`!!window.__sunaDev`, { timeoutMs: 20000, desc: 'window.__sunaDev (dev build)' })

  // Re-open the driver's example copy if a previous run left the app with no
  // project — the probe is re-run often, and having to re-boot between runs
  // is friction the docs build does not need.
  let rootDir = await ctx.evalJs(`window.__sunaDev.projectStore.getState().rootDir`)
  if (!rootDir) {
    const fallback = join(ROOT, 'scripts', 'e2e', '.userdata-drive', 'example-project')
    if (!existsSync(fallback)) {
      throw new Error('no project open — boot with: node scripts/e2e/drive.mjs --boot --example')
    }
    await ctx.evalJs(`window.__sunaDev.openProjectAt(${JSON.stringify(fallback)})`)
    await ctx.waitFor(`!!window.__sunaDev.projectStore.getState().rootDir`, {
      timeoutMs: 20000,
      desc: 'example project reopened'
    })
    rootDir = await ctx.evalJs(`window.__sunaDev.projectStore.getState().rootDir`)
  }

  const dev = (expr) => ctx.evalJs(`window.__sunaDev.${expr}`)
  const setTheme = (t) => dev(`settingsStore.getState().setGlobal('editor.editorTheme', ${JSON.stringify(t)})`)
  const setView = (v) => dev(`uiStore.getState().setActiveView(${JSON.stringify(v)})`)
  const open = (p) => dev(`dock.openFileTab(${JSON.stringify(p)})`)
  const f = (rel) => join(rootDir, rel)

  const captured = []
  const skipped = []

  /**
   * The renderer is served by a Vite dev server that full-reloads whenever a
   * watched file changes — and the app itself writes into the project it has
   * open (figure sidecars, provenance, settings). A reload wipes
   * `window.__sunaDev` and the open project out from under the run. Rather
   * than chase every writer, every shot re-establishes the seam first.
   */
  async function ensureAlive() {
    const live = await ctx.evalJs(`!!window.__sunaDev`)
    if (!live) {
      await ctx.waitFor(`!!window.__sunaDev`, { timeoutMs: 30000, desc: 'renderer back after reload' })
    }
    const open = await ctx.evalJs(`!!window.__sunaDev.projectStore.getState().rootDir`)
    if (!open) {
      await ctx.evalJs(`window.__sunaDev.openProjectAt(${JSON.stringify(rootDir)})`)
      await ctx.waitFor(`!!window.__sunaDev.projectStore.getState().rootDir`, {
        timeoutMs: 30000,
        desc: 'project reopened after reload'
      })
      await ctx.sleep(600)
    }
  }

  /** Reset to a known chrome state so one shot never leaks into the next. */
  async function reset() {
    await dev(`dock.clearDock()`)
    await dev(`uiStore.getState().setHelpOpen(false)`)
    await dev(`uiStore.getState().setCommentsRailVisible(false)`)
    await dev(`uiStore.getState().setSidebarVisible(true)`)
    await dev(`uiStore.getState().setRailVisible(true)`)
    await dev(`uiStore.getState().setSidebarWidth(272)`)
    await ctx.evalJs(`document.activeElement?.blur?.()`)
    // Close the command palette if a previous shot left it up. Escape is
    // handled on the palette's own input, which no longer has focus once the
    // dock is cleared — so dismiss it the way a click outside would.
    await ctx.evalJs(
      `document.querySelector('.palette-backdrop')?.dispatchEvent(new MouseEvent('mousedown', { bubbles: true }))`
    )
    await ctx.sleep(200)
  }

  /**
   * Capture one named shot. `setup` puts the app in the state; `waitFor` is
   * the selector expression that proves the surface actually rendered — a
   * shot that cannot prove itself is skipped loudly rather than saved blank.
   */
  async function shot(name, { setup, waitFor, settle = 900, desc }) {
    if (only.length > 0 && !only.includes(name)) return
    try {
      await ensureAlive()
      await reset()
      await setup()
      if (waitFor) await ctx.waitFor(waitFor, { timeoutMs: 15000, desc: desc ?? name })
      await ctx.sleep(settle)
      await ctx.screenshot(join(STAGE, `${name}.png`))
      captured.push(name)
      console.log(`  ✓ ${name}`)
    } catch (err) {
      skipped.push({ name, error: String(err.message ?? err) })
      console.log(`  ✗ ${name} — ${err.message ?? err}`)
    }
  }

  /**
   * A sidebar-focused shot: widen the rail so its cards are readable, and put
   * the manuscript in the editor area so the shot never shows a dead void
   * where a user's document would be.
   */
  async function sidebarShot(view) {
    await setView(view)
    await dev(`uiStore.getState().setSidebarWidth(400)`)
    await openManuscript()
  }

  /**
   * Open the combined manuscript tab and wait for its title page.
   * clearDock() tears the panel down asynchronously, so a re-open issued in
   * the same tick can land on the dying panel and never mount — retry until
   * the title page is really in the DOM.
   */
  async function openManuscript() {
    for (let attempt = 0; attempt < 4; attempt++) {
      await dev(`dock.openManuscriptTab(${JSON.stringify(rootDir)})`)
      for (let i = 0; i < 20; i++) {
        await ctx.sleep(250)
        if (await ctx.evalJs(`!!document.querySelector('.msdoc__titlepage')`)) return
      }
    }
    throw new Error('combined manuscript tab never mounted (.msdoc__titlepage)')
  }

  /**
   * Seed a short, realistic review thread so the comments rail photographs as
   * the review surface it is. Ids are collected and removed at the end — the
   * example project this probe drives is left exactly as it was found.
   */
  const seeded = []
  async function seedComments() {
    const { readFileSync } = await import('node:fs')
    const text = readFileSync(f('manuscript/manuscript.md'), 'utf8')
    const anchorFor = (quote) => {
      const at = text.indexOf(quote)
      if (at < 0) return null
      return {
        kind: 'section',
        path: 'manuscript.md',
        anchor: {
          prefix: text.slice(Math.max(0, at - 32), at),
          quote,
          suffix: text.slice(at + quote.length, at + quote.length + 32)
        }
      }
    }
    // Two anchors on real prose, long enough that the resolver locks on.
    const lines = text
      .split('\n')
      .filter((l) => !l.startsWith('#') && !l.startsWith('!') && l.trim().length >= 56)
      .map((l) => l.trim().slice(0, 44))

    const threads = [
      {
        quote: lines[0],
        body: 'Can we quantify "a few hundred million years" here? A number with an error bar reads stronger than a range.',
        reply: 'Agreed — the fit in results/spectrum_fit.json gives 240 ± 60 Myr. Rewriting to cite it.'
      },
      {
        quote: lines[2] ?? lines[1],
        body: 'This paragraph carries the whole argument for the environmental channel. Worth splitting the last sentence out.'
      }
    ]
    for (const t of threads) {
      if (!t.quote) continue
      const target = anchorFor(t.quote)
      if (!target) continue
      const created = await ctx.evalJs(
        `window.__sunaDev.commentsStore.getState().add(${JSON.stringify(target)}, ${JSON.stringify(t.body)})`
      )
      if (created && typeof created.id === 'string') {
        seeded.push(created.id)
        if (t.reply) {
          await ctx.evalJs(
            `window.__sunaDev.commentsStore.getState().reply(${JSON.stringify(created.id)}, ${JSON.stringify(t.reply)})`
          )
        }
      }
    }
    if (seeded[0]) {
      await ctx.evalJs(`window.__sunaDev.commentsStore.getState().setActive(${JSON.stringify(seeded[0])})`)
    }
  }

  const applyTheme = async (t) => {
    await ensureAlive()
    await setTheme(t)
    await ctx.sleep(700)
  }

  /**
   * Drop every remembered project from the driver's settings.
   *
   * The welcome screen lists recent projects by absolute path, and these
   * captures are published on a public website — a shot of that list would
   * ship the developer's home directory and the names of unrelated private
   * projects. The list is cleared before it is photographed, so the shot shows
   * the genuine empty state and nothing personal can leak into the docs.
   */
  async function clearRecents() {
    const { recents } = await ctx.evalJs(`window.suna.invoke('project:recents', {})`)
    for (const entry of recents ?? []) {
      await ctx.evalJs(
        `window.suna.invoke('project:forget-recent', { path: ${JSON.stringify(entry.path)} })`
      )
    }
  }

  console.log(`capturing docs shots → ${OUT}`)
  await applyTheme('suna-dark')

  // ---------------------------------------------------------------- welcome
  await shot('welcome', {
    setup: async () => {
      await clearRecents()
      await dev(`dock.openWelcomeTab()`)
    },
    waitFor: `!!document.querySelector('.welcome__title')`
  })

  // ------------------------------------------------- manuscript: source mode
  await shot('manuscript-source', {
    setup: async () => {
      await setView('explorer')
      await open(f('manuscript/manuscript.md'))
      await ctx.waitFor(`!!document.querySelector('.cm-content')`, { timeoutMs: 15000, desc: 'editor' })
      // Force Source: the mode button is a two-state toggle, so read the label.
      for (let i = 0; i < 3; i++) {
        const label = await ctx.evalJs(`document.querySelector('.editor-tab__mode')?.textContent ?? ''`)
        if (/source/i.test(label)) break
        await ctx.evalJs(`document.querySelector('.editor-tab__mode')?.click()`)
        await ctx.sleep(400)
      }
    },
    waitFor: `(document.querySelector('.cm-content')?.textContent ?? '').length > 200`
  })

  // ------------------------------------------------ manuscript: reading mode
  await shot('manuscript-reading', {
    setup: async () => {
      await setView('explorer')
      await open(f('manuscript/manuscript.md'))
      await ctx.waitFor(`!!document.querySelector('.cm-content')`, { timeoutMs: 15000, desc: 'editor' })
      for (let i = 0; i < 3; i++) {
        const label = await ctx.evalJs(`document.querySelector('.editor-tab__mode')?.textContent ?? ''`)
        if (/reading/i.test(label)) break
        await ctx.evalJs(`document.querySelector('.editor-tab__mode')?.click()`)
        await ctx.sleep(400)
      }
    },
    waitFor: `!!document.querySelector('.cm-content .katex') || !!document.querySelector('.cm-lp-cite')`,
    desc: 'rendered math or citations'
  })

  // ------------------------------------- the combined manuscript document tab
  await shot('manuscript-document', {
    setup: async () => {
      await setView('explorer')
      await openManuscript()
    },
    waitFor: `!!document.querySelector('.msdoc__titlepage')`,
    settle: 1200
  })

  // ------------------------------------------------------------ figure canvas
  await shot('canvas', {
    setup: async () => {
      await setView('figures')
      await open(f('figures/fig-spectrum/figure.svg'))
    },
    waitFor: `!!document.querySelector('.canvas-world svg')`,
    settle: 1400
  })

  await shot('canvas-velocity', {
    setup: async () => {
      await setView('figures')
      await open(f('figures/fig-velocity-map/figure.svg'))
    },
    waitFor: `!!document.querySelector('.canvas-world svg')`,
    settle: 1400
  })

  // ------------------------------------------------------------- references
  await shot('references', {
    setup: async () => {
      await sidebarShot('references')
    },
    waitFor: `!!document.querySelector('.msdoc__titlepage')`,
    settle: 1600
  })

  await shot('bib-source', {
    setup: async () => {
      await setView('references')
      await open(f('manuscript/references.bib'))
    },
    waitFor: `(document.querySelector('.cm-content')?.textContent ?? '').includes('@')`
  })

  // ----------------------------------------------------------- source control
  await shot('source-control', {
    setup: () => sidebarShot('git'),
    waitFor: `!!document.querySelector('.msdoc__titlepage')`,
    settle: 1600
  })

  // ------------------------------------------------------------------- agent
  await shot('agent', {
    setup: () => sidebarShot('agent'),
    waitFor: `!!document.querySelector('.msdoc__titlepage')`,
    settle: 1600
  })

  // ---------------------------------------------------- manuscript outline
  await shot('outline', {
    setup: () => sidebarShot('manuscript'),
    waitFor: `!!document.querySelector('.msdoc__titlepage')`,
    settle: 1600
  })

  // --------------------------------------------------------- comments rail
  await shot('comments', {
    setup: async () => {
      await setView('manuscript')
      await openManuscript()
      await dev(`uiStore.getState().setCommentsRailVisible(true)`)
      await seedComments()
      await ctx.sleep(600)
    },
    waitFor: `document.querySelectorAll('.cmt-card').length > 0`,
    settle: 900
  })

  // --------------------------------------------------------------- data grid
  await shot('data-grid', {
    setup: async () => {
      await setView('explorer')
      await open(f('data/spectrum.csv'))
    },
    waitFor: `document.querySelectorAll('.dataview__table tbody tr').length > 3`,
    settle: 1200
  })

  // ---------------------------------------------------------------- settings
  // Photograph the shipped defaults, not whatever this driver was last left
  // with — a Settings shot with vim motions already on documents a state a
  // reader's fresh install is not in.
  await shot('settings', {
    setup: async () => {
      await dev(`settingsStore.getState().setGlobal('editor.vimMotions', false)`)
      await ctx.sleep(300)
      await dev(`dock.openSettingsTab()`)
    },
    waitFor: `!!document.querySelector('.settings-tab__row')`,
    settle: 1200
  })

  // ------------------------------------------------------------------ export
  // The export tab reads the loaded manuscript; open the manuscript first or
  // it photographs its own empty state ("No manuscript to export…").
  await shot('export', {
    setup: async () => {
      await setView('explorer')
      // The dialog reads useManuscriptStore, which only fills once something
      // has asked it to — the dock alone does not.
      await dev(`manuscriptStore.getState().refresh()`)
      await ctx.waitFor(`!!window.__sunaDev.manuscriptStore.getState().manuscript`, {
        timeoutMs: 10000,
        desc: 'manuscript loaded'
      })
      // Go through the real command, not dock.openExportTab() — the panel
      // reads rootDir from its params, and only the command supplies them.
      await dev(`commands.runCommand('manuscript.export')`)
    },
    waitFor: `!!document.querySelector('.export-dialog__form')`,
    settle: 1600
  })

  // -------------------------------------------------------- command palette
  await shot('command-palette', {
    setup: async () => {
      await setView('explorer')
      await open(f('manuscript/manuscript.md'))
      await ctx.sleep(700)
      // CDP modifier bits: Alt 1, Ctrl 2, Meta 4, Shift 8 — ⌘⇧P is 12.
      await ctx.key('P', 'KeyP', 12)
      await ctx.sleep(300)
    },
    waitFor: `!!document.querySelector('.palette-backdrop .palette__list')`,
    settle: 600
  })

  // ------------------------------------------------------ keyboard shortcuts
  await shot('shortcuts', {
    setup: async () => {
      await setView('explorer')
      await open(f('manuscript/manuscript.md'))
      await ctx.sleep(500)
      await dev(`uiStore.getState().setHelpOpen(true)`)
    },
    waitFor: `!!document.querySelector('.help-overlay__body')`,
    settle: 700
  })

  // ------------------------------------------------------------- light theme
  await applyTheme('suna-light')

  await shot('manuscript-reading-light', {
    setup: async () => {
      await setView('manuscript')
      await openManuscript()
    },
    waitFor: `!!document.querySelector('.msdoc__titlepage')`,
    settle: 1200
  })

  await shot('canvas-light', {
    setup: async () => {
      await setView('figures')
      await open(f('figures/fig-spectrum/figure.svg'))
    },
    waitFor: `!!document.querySelector('.canvas-world svg')`,
    settle: 1400
  })

  // ---------------------------------------------------------------- gruvbox
  await applyTheme('gruvbox')
  await shot('theme-gruvbox', {
    setup: async () => {
      await setView('explorer')
      await open(f('manuscript/manuscript.md'))
    },
    waitFor: `!!document.querySelector('.cm-content')`,
    settle: 1000
  })

  // ------------------------------------------------------------- jellybeans
  await applyTheme('jellybeans')
  await shot('theme-jellybeans', {
    setup: async () => {
      await setView('explorer')
      await open(f('manuscript/manuscript.md'))
    },
    waitFor: `!!document.querySelector('.cm-content')`,
    settle: 1000
  })

  // leave the app — and the example project — the way we found them
  await applyTheme('suna-dark')
  for (const id of seeded) {
    await ctx.evalJs(`window.__sunaDev.commentsStore.getState().remove(${JSON.stringify(id)})`)
  }
  await reset()

  // Land every staged PNG in one burst, now that nothing depends on the page.
  for (const file of readdirSync(STAGE)) copyFileSync(join(STAGE, file), join(OUT, file))
  rmSync(STAGE, { recursive: true, force: true })

  return { out: OUT, captured, skipped, seededCommentsRemoved: seeded.length }
}
