export type { Author, BibEntry, LiteralAuthor, PersonAuthor, Run, RunLink } from './model.js';
export { detectArxivId } from './model.js';
export type { ParseIssue, ParseResult } from './parse.js';
export { parseBibtex } from './parse.js';
export { serializeBibtex, serializeEntry } from './serialize.js';
export type { CitationCluster, CitationMode, CitationStyleConfig, CiteRendering } from './cite.js';
export { assignNumbers, renderCluster } from './cite.js';
export type { BibFormatConfig } from './format.js';
export { formatReference } from './format.js';
export { generateCiteKey, litResultToBibEntry } from './lit-entry.js';
export type { LitLookupOutcome, LitRequestOptions, LitSearchOutcome } from './providers.js';
export { lookupByDoi, searchLiterature } from './providers.js';
export type { AppendLitResultOutcome } from './bib-write.js';
export { appendLitResultToBib } from './bib-write.js';
