/**
 * Pure template strings for the agent context layer: the per-project stub
 * (AGENTS.md / CLAUDE.md), the project memory files (context/), and the
 * machine-level UserContext seeds. No I/O here — ensure.ts owns all writes,
 * and the wizard preview can import these without touching the file system.
 */

/** Fixed name of the per-project memory directory (deliberately NOT in
 * suna.json's `directories` record — it is an agent-layer convention, not a
 * relocatable data directory, and adding a manifest key would force a schema
 * migration for zero benefit). */
export const PROJECT_CONTEXT_DIR = 'context'

export const PROJECT_CONTEXT_FILES = ['MISSION.md', 'NOTEBOOK.md', 'RULES.md'] as const

/**
 * First line of every generated stub. The version marker is the heal
 * contract: while a stub's first line matches STUB_MARKER_RE, SUNA may
 * rewrite the file on open; a user who deletes the marker (or replaces the
 * file) owns it forever after.
 */
const STUB_MARKER =
  '<!-- suna:agent-stub v1 — generated by SUNA; edit freely, delete this marker line to opt out of updates -->'

const STUB_MARKER_RE = /^<!-- suna:agent-stub v\d+ /

/** True when `text` is a SUNA-generated stub this layer is allowed to rewrite. */
export function isManagedStub(text: string): boolean {
  const firstLine = text.slice(0, text.indexOf('\n') + 1 || undefined)
  return STUB_MARKER_RE.test(firstLine.trim())
}

/** The AGENTS.md / CLAUDE.md stub — identical content in both files, so
 * Codex (AGENTS.md) and Claude Code (CLAUDE.md) read the same pointer. */
export function agentStub(): string {
  return `${STUB_MARKER}

# Agents: read the context folders

This is a SUNA project — an academic manuscript with managed figures,
references, and review comments, all plain text. Agent instructions, user
context, and project memory live in two places:

1. **Machine level:** \`~/SunaConfig/Context/\` (or \`$SUNA_CONFIG_DIR/Context/\`
   when that variable is set) — who the user is (\`UserContext/\`) and how to
   work with SUNA projects (\`SunaContext/\` — start with its \`README.md\`; the
   session playbook is \`SunaContext/WORKFLOW.md\`).
2. **Project level:** \`context/\` in this folder — the mission
   (\`MISSION.md\`), the running notebook (\`NOTEBOOK.md\`), and this project's
   rules (\`RULES.md\`). Read all three before working.

SUNA's manuscript tools reach agents via \`.mcp.json\` in this folder
(machine-local, not committed; the verb reference is \`SunaContext/MCP.md\`).
If \`.mcp.json\` is missing, open the project in SUNA once — it heals on open.
`
}

const MANAGED_COMMENT_OPEN = '<!--'

/** context/MISSION.md — the co-owned project charter. */
export function missionTemplate(projectName: string): string {
  const name = projectName.trim() === '' ? 'this project' : projectName.trim()
  return `# Mission — ${name}

${MANAGED_COMMENT_OPEN} The project charter: what we are doing and why. Co-owned by the user
     and the agent — an agent may draft from the user's answers; the user
     corrects in place or via comments and has final say. Agents read this
     before working. -->

## Question

What are we trying to learn?

## Data

What data exists, where it lives, and what shape it is in.

## Prior work

What has already been done (analyses, code, figures, drafts) before this
project.

## Deliverable

What we are producing (paper, report), for what venue and audience, and what
"done" looks like.

## Scope and non-goals

What is explicitly in and out of scope.
`
}

/** context/NOTEBOOK.md — the agent's memory of the project. */
export function notebookTemplate(): string {
  return `# Project notebook

${MANAGED_COMMENT_OPEN} The agent's memory of this project. Agent-owned: agents write; the
     user reads and leaves comments. Body = current truth, edited in place
     with surgical anchored edits — never a whole-file rewrite. Session log =
     append-only history, newest last. -->

## State

*(Current state of the manuscript and figures — kept true by the agent.)*

## Decisions

*(Decisions in force, each with its why.)*

## Tried

*(What has been attempted and what happened — including dead ends.)*

## Open questions

*(Unresolved items, for the human or for future work.)*

---

## Session log

*(Append-only, newest last: \`### YYYY-MM-DD HH:MM — title\` + a concise entry.)*
`
}

/** context/RULES.md — co-owned standing rules for this project. */
export function rulesTemplate(): string {
  return `# Project rules

${MANAGED_COMMENT_OPEN} Standing rules for THIS project only. Co-owned: the user writes rules
     here, and an agent promotes the user's recurring feedback into rules
     here. Global rules (all projects) live in
     ~/SunaConfig/Context/UserContext/RULES.md. -->

- *(none yet)*
`
}

/** UserContext/WHO-AM-I.md — seeded once, user-owned forever after. */
export const WHO_AM_I_SEED = `# Who am I

${MANAGED_COMMENT_OPEN} Yours to fill in — agents read this before working for you: your
     background, field, position, expertise, interests, and taste; whatever an
     agent should know to write and plot the way you would. -->

*(not filled out yet)*
`

/** UserContext/RULES.md — seeded once, user-owned forever after. */
export const USER_RULES_SEED = `# Standing rules — all SUNA projects

${MANAGED_COMMENT_OPEN} Yours to edit; agents may PROPOSE additions but never write here
     unasked. Rules that apply to every project: writing style, figure
     conventions, workflow preferences. Project-specific rules live in each
     project's context/RULES.md. -->

- *(none yet)*
`

/** Marker inside the synced skill file; a user who removes it (or replaces
 * the file) opts out of skill updates, mirroring the stub contract. */
export const SKILL_MARKER = '<!-- suna:managed-skill'
